#!/bin/bash

cat log.txt | grep error >temp.txt

error_type=()

error_info=()

error_count=()

error_time=()

while read line

do
	errorline=${line:60}

	errortime=${line:0:15}

	errortype=${errorline%%:*}

	errorinfo=${errorline##*:}

	#echo $errortime

	#echo $errortype 

	#echo $errorinfo

	mark="NO"	



	for(( i=0;i<${#error_type[@]};i++))

		do


			#echo ${error_type[$i]} ${error_type[$i]}

			if [ "${error_type[$i]}" == "$errortype" ];then

			error_type[$i]=$errortype 

			error_info[$i]=$errorinfo

			#echo ${error_count[$i]}

			error_count[$i]=`expr ${error_count[$i]} + 1`

			error_time[$i]=${error_time[$i]}" "$errortime

			mark="YES"

			#echo "YES"

			break;

			fi	

	done


	if [ "$mark" == "YES" ];then

		continue

	fi	


	error_type[${#error_type[*]}]=$errortype 

	error_info[${#error_info[*]}]=$errorinfo

	error_time[${#error_time[*]}]=$error_time 

	error_count[${#error_count[*]}]="1"

#	echo "add.."

done < temp.txt

echo "type:" ${error_type[@]}

echo "info:" ${error_info[@]}

echo "count:" ${error_count[@]}

echo "time:"${error_time[@]}
